---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sources-volume-claim
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      for: sources
  resources:
    requests:
      storage: 2Gi
